---
title: "neil"
author: "Neil Khurana"
date: "April 13, 2019"
output: html_document
---

```{r setup, include=FALSE, message = FALE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE) 
library(gsheet)
library(tidyverse)
library(ggplot2)
```


```{r huds}
hudsdata<-gsheet2tbl('https://docs.google.com/spreadsheets/d/1S3vFDul1PeB84Zd8G5ewe1ocZ6ezidQzAp5gn1eiHtQ/edit#gid=0')
```

```{r breakfast, echo = FALSE}
breakfast_frequency <- hudsdata %>% 
  filter(Meal == "Breakfast") %>% 
  group_by(Food) %>% 
  summarize(count=n()) %>% 
  arrange(desc(count)) %>% 
  slice(1:5)  
hudsdata$Date[1]
ggplot(breakfast_frequency, aes(x = Food, y = count, color = Food, fill = Food)) +
  geom_bar(stat = "identity") +
  labs(x = "Food Item", y = "Frequency", title = "Top Five Most Frequent Breakfast Items by HUDS", caption = paste("Data collected from 11/10/2018 -", \n 
       Source: Harvard University Dining Services") +
  theme(legend.position = "none")
```

```{r lunch, echo = FALSE}
lunch_frequency_plot <- hudsdata %>% 
  filter(Meal == "Lunch") %>% 
  group_by(Food) %>% 
  summarize(count=n()) %>% 
  arrange(desc(count)) %>%
  slice(1:5) 

ggplot(lunch_frequency_plot, aes(x = Food, y = count, color = Food, fill = Food)) +
  geom_bar(stat = "identity") +
  labs(x = "Food Item", y = "Frequency", title = "Top Five Most Frequent Lunch Items by HUDS", caption ="Data collected from 11/10/2018 - 4/13/2019 \n 
       Source: Harvard University Dining Services") +
  theme(legend.position = "none")
```

```{r dinner, echo = FALSE}
dinner_frequency_plot <- hudsdata %>% 
  filter(Meal == "Dinner") %>% 
  group_by(Food) %>% 
  summarize(count=n()) %>% 
  arrange(desc(count)) %>% 
  slice(1:5) 

ggplot(dinner_frequency_plot, aes(x = Food, y = count, color = Food, fill = Food)) +
  geom_bar(stat = "identity") +
  labs(x = "Food Item", y = "Frequency", title = "Top Five Most Frequent Dinner Items by HUDS", caption ="Data collected from 11/10/2018 - 4/13/2019 \n 
       Source: Harvard University Dining Services") +
  theme(legend.position = "none")
```